### ISSUE TITLE
Scrolling Error on Salesforce Mobile

### ISSUE THREAD

**Issue by briancodey** [effordDev/sf-calendar#10]
I added the Custom Calendar to an App page.  Desktop version worked fine.

When I tested in Salesforce Mobile, the Custom Calendar loaded, but as soon as I tried to scroll the calendar up, it immediately threw an error: 
`"This page has an error.  You might just need to refresh it.  First, would you give us some details? (We've report this as error ID: -1938395671)."`

Expanded under **Technical Stuff**, I got these: 
`[e.stopImmediatePropogation is not a function. (In 'e.stopImmediatePropogation()', 'e.stopImmediatePropogation' is undefined)] handleScroll() callHook()`

![image](https://github.com/effordDev/sf-calendar/assets/33266591/21e454ac-6a4d-4ec5-a205-16271b891356)

**Comment by effordDev** [comment]
@briancodey thanks, were you by chance able to scroll with the list view on the mobile app?

Ex. 
![image](https://github.com/effordDev/sf-calendar/assets/36901822/fc6e80b8-e162-4991-a9c6-c2094bab1d81)
