### ISSUE TITLE
INVALID_FIELD_FOR_INSERT_UPDATE Error is thrown when flow is triggered

### ISSUE THREAD

**Issue by amohammadict** [effordDev/sf-calendar#11]
I followed the instructions provided and activated the flow. I also made sure I'm choosing the event platform object in the flow (as I'm using the similar labels).
And I receive the below error when the flow triggers:
`This error occurred when the flow tried to create records: INVALID_FIELD_FOR_INSERT_UPDATE: The event can't be published because it contains an ID value.`
When searched for this, it looks like this is an error from Apex. I would appreciate your support in resolving this.
Thanks

**Comment by effordDev** [comment]
Hello @amohammadict, you get this error in salesforce when you are trying to insert a record but specifying the `Id` field with a value. Here is a screenshot of my flow and a screenshot of the create element. Can you share screenshots of what your flow looks like so I can help debug for you? Thanks
![Screenshot 2023-12-08 at 10 22 50 AM](https://github.com/effordDev/sf-calendar/assets/36901822/970de66b-f72c-4858-b5fa-9dbe20cd3768)
![Screenshot 2023-12-08 at 10 25 10 AM](https://github.com/effordDev/sf-calendar/assets/36901822/b8d329b9-bce7-4e4e-b851-7300d96a177d)

**Comment by amohammadict** [comment]
Hi @effordDev Thanks for the screenshots very helpful. I created a custom field Platform Message (Platform_Message__c) and it now works fine. My impression from [this screenshot](https://user-images.githubusercontent.com/36901822/189167019-d924e810-8274-4706-a4d9-275c1086952d.png) was that no field is needed.
